---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.2
    ports:
    - 8080:8080
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      NER_INFERENCE_API: 'http://ner-transformers:8080'
      SUM_INFERENCE_API: 'http://sum-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ENABLED: 'false'
      # AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'akemplerkey'
      # AUTHENTICATION_APIKEY_USERS: 'akempler'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      # DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      # ENABLE_MODULES: 'text2vec-transformers,qna-transformers,ner-transformers,sum-transformers,generative-openai'
      ENABLE_MODULES: 'text2vec-transformers,text2vec-openai,qna-openai,ner-transformers,sum-transformers,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  # qna-transformers:
  #   image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
  #   environment:
  #     ENABLE_CUDA: '1'
  #     NVIDIA_VISIBLE_DEVICES: 'all'
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - capabilities: 
  #           - 'gpu'
  ner-transformers:
    image: semitechnologies/ner-transformers:dbmdz-bert-large-cased-finetuned-conll03-english
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  sum-transformers:
    image: semitechnologies/sum-transformers:facebook-bart-large-cnn-1.0.0
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
volumes:
  weaviate_data:
...